  DROP DATABASE IF EXISTS IvernIt;

  CREATE DATABASE IvernIt;

  USE IvernIt;

  CREATE TABLE usuario (
    uId         INTEGER      AUTO_INCREMENT PRIMARY KEY,
    uNombre     VARCHAR(255) UNIQUE,
    uContrasena VARCHAR(64)  NOT NULL,
    uPremium    TINYINT(1)   NOT NULL
  );

  INSERT INTO usuario(uNombre, uContrasena, uPremium) VALUES('pablo', '26079e41910bcde04be636fbeecc9045379882b5ad3fe7f70b762436c6d98055', 1);
  INSERT INTO usuario(uNombre, uContrasena, uPremium) VALUES('menendez', '2cae32224c8f2416475351adc9923d77ff307c82d899557e2d30c6d71dd63c00', 1);
  INSERT INTO usuario(uNombre, uContrasena, uPremium) VALUES('sampru', 'e7fa886ec38e36629a43367fdd0a42badab224c9047ba5aaba2d4dfb4fcd0623', 0);

  CREATE TABLE invernadero (
    iId     INTEGER AUTO_INCREMENT PRIMARY KEY,
    uId     INTEGER NOT NULL,
    iNombre VARCHAR(255),
    CONSTRAINT FK_usuInv FOREIGN KEY (uId) REFERENCES usuario(uId)
  );

  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(1,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(2,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(3,'testing greenhouse');
  INSERT INTO invernadero(uId,iNombre) VALUES(3,'testing greenhouse');

  CREATE TABLE estadoCrecimiento (
    ecId     INTEGER      AUTO_INCREMENT PRIMARY KEY,
    ecNombre VARCHAR(255) NOT NULL
  );

  INSERT INTO estadoCrecimiento(ecNombre) VALUES('Germinación');
  INSERT INTO estadoCrecimiento(ecNombre) VALUES('Ahijamiento');
  INSERT INTO estadoCrecimiento(ecNombre) VALUES('Gran crecimiento');
  INSERT INTO estadoCrecimiento(ecNombre) VALUES('Maduracion');

  CREATE TABLE vegetal (
    vId     INTEGER      AUTO_INCREMENT PRIMARY KEY,
    vNombre VARCHAR(255) NOT NULL,
    ecId    INTEGER      NOT NULL,
    CONSTRAINT FK_vegIdEst FOREIGN KEY (ecId) REFERENCES estadoCrecimiento(ecId)    
  );

  INSERT INTO vegetal(vNombre, ecId) VALUES('Tomate',1);
  INSERT INTO vegetal(vNombre, ecId) VALUES('Tomate',2);
  INSERT INTO vegetal(vNombre, ecId) VALUES('Tomate',3);
  INSERT INTO vegetal(vNombre, ecId) VALUES('Tomate',4);
  INSERT INTO vegetal(vNombre, ecId) VALUES('Patata',1);
  INSERT INTO vegetal(vNombre, ecId) VALUES('Patata',2);
  INSERT INTO vegetal(vNombre, ecId) VALUES('Patata',3);
  INSERT INTO vegetal(vNombre, ecId) VALUES('Patata',4);
  INSERT INTO vegetal(vNombre, ecId) VALUES('Cebolla',1);
  INSERT INTO vegetal(vNombre, ecId) VALUES('Cebolla',2);
  INSERT INTO vegetal(vNombre, ecId) VALUES('Cebolla',3);
  INSERT INTO vegetal(vNombre, ecId) VALUES('Cebolla',4);
  INSERT INTO vegetal(vNombre, ecId) VALUES('Pimiento',1);
  INSERT INTO vegetal(vNombre, ecId) VALUES('Pimiento',4);

  CREATE TABLE parametro (
    pId          INTEGER      AUTO_INCREMENT PRIMARY KEY,
    pAgua        DOUBLE       NOT NULL,
    pHorasLuz    DOUBLE       NOT NULL,
    pTemperatura DOUBLE       NOT NULL,
    pTipoTierra  VARCHAR(255) NOT NULL
  );

  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,11,31,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,11,20,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,9,24,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,10,22,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,7,28,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,8,19,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,13,20,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,7,28,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,12,22,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,12,26,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,9,29,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,10,21,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,9,26,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,7,25,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,9,25,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,9,23,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,10,21,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,8,31,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,13,22,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,8,27,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,13,28,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,13,20,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,7,19,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,7,22,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,11,26,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,7,28,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,9,26,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,7,24,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,9,31,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,10,25,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,13,31,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,13,25,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,10,23,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,11,30,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,10,29,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,8,28,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,12,22,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,13,29,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,11,22,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,13,31,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,10,22,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,10,28,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,11,31,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,7,30,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,13,30,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,9,21,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,7,30,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,7,19,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,9,19,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,9,30,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,9,26,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,8,31,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,11,25,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,12,29,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,13,24,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,11,21,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,7,24,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,13,22,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,8,24,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,8,26,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,8,24,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,7,27,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,12,21,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,8,28,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,7,26,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,10,28,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,9,31,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,10,20,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,12,27,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,13,24,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,10,20,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,8,25,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,9,23,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,12,28,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,9,29,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,9,21,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,12,21,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,13,28,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,7,24,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,11,28,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,7,24,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,13,29,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,12,23,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,10,27,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,9,22,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,12,30,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,8,20,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,10,19,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,8,20,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,8,22,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,13,19,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,7,23,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,11,25,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,8,19,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,13,30,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,11,23,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,12,25,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,8,22,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,9,28,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,12,26,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,8,20,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,7,31,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,8,21,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,10,30,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,7,19,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,8,30,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,7,24,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,8,20,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,7,28,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,13,24,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,10,19,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,9,23,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,13,20,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,8,26,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,10,25,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,13,29,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,13,23,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,10,27,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,8,25,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,12,21,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,11,21,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,12,22,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,12,21,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,12,26,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,13,22,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,12,31,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,12,31,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,10,21,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,10,27,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,7,23,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,13,25,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,11,29,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,12,28,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,11,29,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,10,24,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,8,19,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,7,23,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,11,29,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,8,24,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,10,28,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,13,22,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,10,25,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,10,19,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,12,22,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,12,23,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,9,28,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,13,27,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,9,27,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,12,25,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,10,25,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,8,30,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,8,27,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,12,22,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,12,30,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,7,26,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,8,29,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,7,27,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,12,25,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,8,24,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,12,19,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,11,28,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,13,26,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,7,22,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,11,23,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,11,19,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,10,30,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,12,26,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,10,26,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,13,28,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,10,30,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,12,19,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,9,27,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,8,30,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,12,25,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,9,21,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,8,20,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,8,27,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,9,27,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,7,29,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,13,26,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,11,26,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,13,31,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,12,23,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,10,28,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,11,23,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,8,31,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,13,23,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,7,23,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,10,29,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,7,20,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,8,24,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,13,30,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,7,21,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(5,9,21,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,11,21,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,13,19,"margoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(4,13,28,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(6,10,25,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(8,9,31,"gredoso");
  INSERT INTO parametro(pAgua, pHorasLuz, pTemperatura, pTipoTierra) VALUES(7,9,23,"gredoso");

  CREATE TABLE cultivo (
    cId          INTEGER,
    vId          INTEGER,
    pId          INTEGER,
    iId          INTEGER,
    cFechaInicio DATE NOT NULL,
    cResultado   CHAR(1),
    CONSTRAINT PK_culInv    PRIMARY KEY (cId,vId,pId,iId),
    CONSTRAINT FK_culInvVeg FOREIGN KEY (vId) REFERENCES vegetal(vId),
    CONSTRAINT FK_culInvPar FOREIGN KEY (pId) REFERENCES parametro(pId),
    CONSTRAINT FK_culInvInv FOREIGN KEY (iId) REFERENCES invernadero(iId)
  );

  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(1,1,1,1,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(2,1,2,2,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(3,1,3,3,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(4,1,4,4,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(5,1,5,5,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(6,1,6,6,'2017-01-02','A');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(7,1,7,7,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(8,1,8,8,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(9,1,9,9,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(10,1,10,10,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(11,1,11,11,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(12,1,12,12,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(13,1,13,13,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(14,1,14,14,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(15,1,15,15,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(16,1,16,16,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(17,1,17,17,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(18,1,18,18,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(19,1,19,19,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(20,1,20,20,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(21,1,21,21,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(22,1,22,22,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(23,1,23,23,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(24,1,24,24,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(25,1,25,25,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(26,1,26,26,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(27,1,27,27,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(28,1,28,28,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(29,1,29,29,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(30,1,30,30,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(31,1,31,31,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(32,1,32,32,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(33,1,33,33,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(34,1,34,34,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(35,1,35,35,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(36,1,36,36,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(37,1,37,37,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(38,1,38,38,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(39,1,39,39,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(40,1,40,40,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(41,1,41,41,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(42,1,42,42,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(43,1,43,43,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(44,1,44,44,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(45,1,45,45,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(46,1,46,46,'2017-01-02','A');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(47,1,47,47,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(48,1,48,48,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(49,1,49,49,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(50,1,50,50,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(51,1,51,51,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(52,1,52,52,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(53,1,53,53,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(54,1,54,54,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(55,1,55,55,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(56,1,56,56,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(57,1,57,57,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(58,1,58,58,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(59,1,59,59,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(60,1,60,60,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(61,1,61,61,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(62,1,62,62,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(63,1,63,63,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(64,1,64,64,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(65,1,65,65,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(66,1,66,66,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(67,1,67,67,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(68,1,68,68,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(69,1,69,69,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(70,1,70,70,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(71,1,71,71,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(72,1,72,72,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(73,1,73,73,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(74,1,74,74,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(75,1,75,75,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(76,1,76,76,'2017-01-02','A');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(77,1,77,77,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(78,1,78,78,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(79,1,79,79,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(80,1,80,80,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(81,1,81,81,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(82,1,82,82,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(83,1,83,83,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(84,1,84,84,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(85,1,85,85,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(86,1,86,86,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(87,1,87,87,'2017-01-02','A');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(88,1,88,88,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(89,1,89,89,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(90,1,90,90,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(91,1,91,91,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(92,1,92,92,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(93,1,93,93,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(94,1,94,94,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(95,1,95,95,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(96,1,96,96,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(97,1,97,97,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(98,1,98,98,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(99,1,99,99,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(100,1,100,100,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(101,1,101,101,'2017-01-02','A');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(102,1,102,102,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(103,1,103,103,'2017-01-02','A');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(104,1,104,104,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(105,1,105,105,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(106,1,106,106,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(107,1,107,107,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(108,1,108,108,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(109,1,109,109,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(110,1,110,110,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(111,1,111,111,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(112,1,112,112,'2017-01-02','A');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(113,1,113,113,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(114,1,114,114,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(115,1,115,115,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(116,1,116,116,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(117,1,117,117,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(118,1,118,118,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(119,1,119,119,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(120,1,120,120,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(121,1,121,121,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(122,1,122,122,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(123,1,123,123,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(124,1,124,124,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(125,1,125,125,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(126,1,126,126,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(127,1,127,127,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(128,1,128,128,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(129,1,129,129,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(130,1,130,130,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(131,1,131,131,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(132,1,132,132,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(133,1,133,133,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(134,1,134,134,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(135,1,135,135,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(136,1,136,136,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(137,1,137,137,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(138,1,138,138,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(139,1,139,139,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(140,1,140,140,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(141,1,141,141,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(142,1,142,142,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(143,1,143,143,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(144,1,144,144,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(145,1,145,145,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(146,1,146,146,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(147,1,147,147,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(148,1,148,148,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(149,1,149,149,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(150,1,150,150,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(151,1,151,151,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(152,1,152,152,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(153,1,153,153,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(154,1,154,154,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(155,1,155,155,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(156,1,156,156,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(157,1,157,157,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(158,1,158,158,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(159,1,159,159,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(160,1,160,160,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(161,1,161,161,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(162,1,162,162,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(163,1,163,163,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(164,1,164,164,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(165,1,165,165,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(166,1,166,166,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(167,1,167,167,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(168,1,168,168,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(169,1,169,169,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(170,1,170,170,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(171,1,171,171,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(172,1,172,172,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(173,1,173,173,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(174,1,174,174,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(175,1,175,175,'2017-01-02','A');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(176,1,176,176,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(177,1,177,177,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(178,1,178,178,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(179,1,179,179,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(180,1,180,180,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(181,1,181,181,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(182,1,182,182,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(183,1,183,183,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(184,1,184,184,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(185,1,185,185,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(186,1,186,186,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(187,1,187,187,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(188,1,188,188,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(189,1,189,189,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(190,1,190,190,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(191,1,191,191,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(192,1,192,192,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(193,1,193,193,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(194,1,194,194,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(195,1,195,195,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(196,1,196,196,'2017-01-02','B');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(197,1,197,197,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(198,1,198,198,'2017-01-02','D');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(199,1,199,199,'2017-01-02','C');
  INSERT INTO cultivo(cId, vId, pId, iId, cFechaInicio, cResultado) VALUES(200,1,200,200,'2017-01-02','C');

  CREATE USER 'ivernit'@'*' IDENTIFIED BY '1vern1t';
  GRANT SELECT, INSERT,  ON IvernIt.* TO 'ivernit'@'*';
  FLUSH PRIVILEGES;
